### ISSUE TITLE
Building for iOS, but the linked library 'libktx_read.a' was built for iOS Simulator.

### ISSUE THREAD

**Issue by iamnewaplayer** [atteneder/KtxUnity#72] opened 2022-11-14 09:12 UTC
/Volumes/ShareDisk//IOS/Unity-iPhone.xcodeproj Building for iOS, but the linked library 'libktx_read.a' was built for iOS Simulator.
what can i do for this

**Comment by atteneder** [comment] 2022-11-14 10:10
Hi and thanks for reporting,

I've added iOS simulator binaries in 1.3.0 and 2.2.1 respectively, having tested that it works both in simulator and on device.

You seem to have a conflict of the libraries now. Can you share which versions of KtxUnity, Unity and Xcode your are using?

**Comment by atteneder** [comment] 2022-11-14 10:47
How did you install KtxUnity?

If you cloned it from GitHub (or downloaded a ZIP), make sure the binaries are properly fetched (since they are GIT LFS files).

**Comment by iamnewaplayer** [comment] 2022-11-14 13:16
i try copy *.a to Simulator dir 
it is ok

**Comment by Elyptos** [comment] 2022-11-30 15:58
Hello everyone.

I am also experiencing the same issue on my end. 

XCode version: 13.4.1
Unity version: 2021.3.11
KtxUnity version: 2.2.2

KtxUnitx was installed using Unity´s package manager and openupm.

I can confirm that Unity exports all binaries (simulator and device) during xcode generation, but Xcode tries to build the project with the simulator binaries instead of the device binaries.

Deleting the simulator binaries inside the xcode project solved the problem for me. I do not know if there is a way to tell xcode which binaries to build or if I am missing a setup step.

**Comment by atteneder** [comment] 2022-12-02 15:28
> Hello everyone.
> 
> I am also experiencing the same issue on my end.
> 
> XCode version: 13.4.1 Unity version: 2021.3.11 KtxUnity version: 2.2.2
> 
> KtxUnity was installed using Unity´s package manager and openupm.
> 
> I can confirm that Unity exports all binaries (simulator and device) during xcode generation, but Xcode tries to build the project with the simulator binaries instead of the device binaries.
> 
> Deleting the simulator binaries inside the xcode project solved the problem for me. I do not know if there is a way to tell xcode which binaries to build or if I am missing a setup step.

@Elyptos Thanks for the feedback.

Any chance you could try Xcode 14.1 ? I'm asking, since I don't have a problem and we should find out why.

Thanks

**Comment by atteneder** [comment] 2024-01-31 09:40
I finally know a proper solution that was applied in another package. The fix will come in an update soon&trade;.

**Comment by atteneder** [comment] 2024-03-01 08:53
Fixed in [KTX for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.ktx@latest/) 3.3.0! Please transition to that package, as it is the official successor.

## Full list of changes
### Added
- Embedded Linux support
- Apple tvOS support
- Android x86 and x86_64 support
- Runtime tests that load KTX 2.0 files

### Changed
- Moved Editor scripts into namespace `KtxUnity.Editor`
- Updated binaries to version 1.2.1.

### Fixed
- Code format in markdown files
- Apple iOS device and simulator SDK binaries are properly included/excluded, depending on target SDK.
- Compilation succeeds on non-supported platforms
- `System.EntryPointNotFoundException` for symbols `ktx_get_image_offset` and `ktx_get_image_size` on Windows.
- Using GraphicsFormatUsage (instead of the obsolete FormatUsage) in 2023.2 or newer.
- Crashes and undefined behavior caused by incorrect marshaling when using the IL2CPP scripting.

**Closed by atteneder** 2024-03-01 08:53 UTC
Labels: bug
