### ISSUE TITLE
Android x86_64 support

### ISSUE THREAD

**Issue by Babilinski** [atteneder/KtxUnity#87] opened 2023-08-03 02:25 UTC
Would it be possible to make this package compatible with Android x86_64? I couldn't find instructions on how to compile the plugin manually, otherwise I would gladly open a pull request to add support for this architecture.

**Comment by atteneder** [comment] 2024-01-31 09:16
Absolutely! It's scheduled for the next release of [KTX for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.ktx@latest/), this package's successor.

**Comment by tehwalris** [comment] 2024-02-23 11:17
I've built a Android x86_64 DLL myself according to [these instructions](https://github.com/atteneder/KtxUnity/issues/71#issuecomment-1313386943) as a workaround. It seems to work fine. You can add it to your `Assets/Plugins` folder, adjust the import settings, and keep using the upstream KtxUnity package.

[ktx_unity_1787bf6_android_x86_64.zip](https://github.com/atteneder/KtxUnity/files/14384578/ktx_unity_1787bf6_android_x86_64.zip)

**Comment by atteneder** [comment] 2024-02-23 14:16
Although I appreciate the offer a lot, I respectfully have to decline due to security concerns.

But the good news is it was already merged in the internal development branch. Expect release 3.3.0 next week latest.

**Comment by tehwalris** [comment] 2024-02-23 16:53
Ah I didn't mean this as an offer to include my binary in the repo, of course that's a bad idea. It was more that others who see this issue know that building works. Good to hear that there'll be an official binary soon.

**Comment by atteneder** [comment] 2024-03-01 08:48
[KTX for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.ktx@latest/) 3.3.0 was released! Please transition to that package, as it is the official successor.

## Changes
### Added
- Embedded Linux support
- Apple tvOS support
- Android x86 and x86_64 support
- Runtime tests that load KTX 2.0 files

### Changed
- Moved Editor scripts into namespace `KtxUnity.Editor`
- Updated binaries to version 1.2.1.

### Fixed
- Code format in markdown files
- Apple iOS device and simulator SDK binaries are properly included/excluded, depending on target SDK.
- Compilation succeeds on non-supported platforms
- `System.EntryPointNotFoundException` for symbols `ktx_get_image_offset` and `ktx_get_image_size` on Windows.
- Using GraphicsFormatUsage (instead of the obsolete FormatUsage) in 2023.2 or newer.
- Crashes and undefined behavior caused by incorrect marshaling when using the IL2CPP scripting.

**Closed as completed by atteneder** 2024-03-01 08:48 UTC
Labels: enhancement
