### ISSUE TITLE
KTX2 not supported?

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/KtxUnity#16] opened 2020-09-10 23:50 UTC
I think this is related to #5; I tried loading a file that has etc1s textures created with https://gltf-transform.donmccurdy.com/cli.html (which in turn uses https://github.com/KhronosGroup/KTX-Software/releases) and get errors for failed transcoding:

![image](https://user-images.githubusercontent.com/2693840/92826186-b4c86300-f3d0-11ea-83fd-3a1e015d4745.png)

It seems the textures have mime type ktx2 and contain basis. Is there something I'm doing wrong? I verified that the files work with the babylon sandbox, and also that loading basis files generated with basisu works.

I attached a file for reference (tried with multiple):
[Schreibkugel-etc1s.glb.zip](https://github.com/atteneder/KtxUnity/files/5205156/Schreibkugel-etc1s.glb.zip)

**Comment by atteneder** [comment] 2020-09-18 12:55
Thanks for reporting!

KtxUnity uses quite outdated binaries of KTX2-Software. It could still be an ordinary bug, but I'd like to prepare an updated ktx library first.

**Comment by atteneder** [comment] 2020-09-30 23:04
Today I prototyped new native libraries (since a lot changed in the last months, I had to re-think the build and source somewhat).

I can confirm that all outdated KTX files (created in April) cause the updated library to crash (Unity Editor macOS), but using re-encoding versions of the same textures with an up-to-date `toktx` works!

Since your demo file works now, it's safe to say my assumptions were right:
<img width="632" alt="grafik" src="https://user-images.githubusercontent.com/2593014/94748562-e2764b80-0381-11eb-9617-1b6001e22c58.png">

Since the KTX extension is about to be ratified I'll try to finish off this fix soon, but it'll take some time to have it working and tested on all platforms.

regards,
Andi

**Comment by hybridherbst** [comment] 2020-10-01 00:23
That's awesome! Let me know if you'd like help testing; I'm particularily interested in Windows Desktop and Android support, so happy to test drive those once you say it's ready to be tested.

**Comment by atteneder** [comment] 2020-10-09 13:53
I'm working on the native libs for all platforms, but macOS, iOS, Windows and Linux should work already. Find the recent builds here:

https://github.com/atteneder/KTX-Software-Unity/actions

I'll close this issue once the updated native libs are pushed in this repo.

**Comment by hybridherbst** [comment] 2020-10-09 15:44
Ah, awesome. I'd be especially interested in Windows + Android, can test with Windows first of course!

**Comment by DerrickBarra** [comment] 2020-10-12 19:00
@atteneder Our team is integrating KtxUnity into our WebGL/Android/iOS project, so we'll be happy to test.

**Comment by atteneder** [comment] 2020-10-19 13:11
@DerrickBarra Thanks for the offer!

I've been testing WebGL and iOS successfully now and the binaries for those platforms are already built by the CI (see link above).

Currently I'm working with Khronos to land Android support in KTX-Software. Should be done this week.

In case you want to jump ahead, the branch I'm working on is this one:
https://github.com/atteneder/KtxUnity/tree/ktx_4.0.0_beta_4

I'll let you know if I make progress.

**Comment by atteneder** [comment] 2020-10-21 23:44
Update:

Did some more fixes and added texture orientation support. Pull the ktx_4.0.0_beta_4 branch to test.

Binaries all platforms (including Android, Windows and Linux) can be loaded:
https://github.com/atteneder/KTX-Software-Unity/actions/runs/320877243

I've tested Android 32/64 and macOS successfully!

I might wait for a breaking change in KTX-Software coming end of this week before publishing binaries. Other than that (and testing Windows/Linux), it's ready!

**Comment by DerrickBarra** [comment] 2020-10-22 14:44
Looking forward to testing with the new binaries, hopefully this fixes some of the [reported bugs](https://github.com/atteneder/KtxUnity/issues/17).

**Comment by atteneder** [comment] 2020-10-22 14:47
They are not updated! Download them separately from the link above.

**Closed** 2020-10-23 10:23 UTC
Labels: bug
