### ISSUE TITLE
Fix compilation for unsupported platforms

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/KtxUnity#69] opened 2022-10-05 14:28 UTC
Currently, when compiling/building to some platforms, KtxUnity will error out:

![image](https://user-images.githubusercontent.com/2693840/194085416-040d2d18-4e5f-4f6f-b580-39b8e1f2755a.png)
Mostly with variations of
```cs
'KtxNativeInstance' does not contain a definition for 'INTERFACE_DLL'
```

This is not ideal; better would be that the platforms are explicitly unsupported but compilation would still work.

I tried setting the flags in the Runtime Ktx.asmdef:
![image](https://user-images.githubusercontent.com/2693840/194085640-2e45a721-899f-4341-94e0-4ada834f7c0d.png)

But that brings follow-up errors in glTFast with it, so might not be as easy as that (there may be ifdefs needed in glTFast as well then).

To test compilation for all platforms, simply add https://openupm.com/packages/com.needle.compilation-visualizer to your project and put it into the testables in manifest.json, then run the editor tests seen in the screenshot above:
```json
  "testables": [
    "com.needle.compilation-visualizer"
  ]
```

**Comment by atteneder** [comment] 2024-03-01 08:50
Fixed in [KTX for Unity](https://docs.unity3d.com/Packages/com.unity.cloud.ktx@latest/) 3.3.0! Please transition to that package, as it is the official successor.

## Full list of changes
### Added
- Embedded Linux support
- Apple tvOS support
- Android x86 and x86_64 support
- Runtime tests that load KTX 2.0 files

### Changed
- Moved Editor scripts into namespace `KtxUnity.Editor`
- Updated binaries to version 1.2.1.

### Fixed
- Code format in markdown files
- Apple iOS device and simulator SDK binaries are properly included/excluded, depending on target SDK.
- Compilation succeeds on non-supported platforms
- `System.EntryPointNotFoundException` for symbols `ktx_get_image_offset` and `ktx_get_image_size` on Windows.
- Using GraphicsFormatUsage (instead of the obsolete FormatUsage) in 2023.2 or newer.
- Crashes and undefined behavior caused by incorrect marshaling when using the IL2CPP scripting.

**Closed by atteneder** 2024-03-01 08:50 UTC
Labels: bug
