### ISSUE TITLE
KTX spoil mesh texture in Unity build with URP but it works in the editor 

### ISSUE THREAD

**Issue by Ashot1705** [atteneder/KtxUnity#88] opened 2023-10-23 08:53 UTC
I work on Unity 2022.3.9f , I use gltfast with ktx and draco, but model mesh texture spoils in unity builds(webgl,android apk) , but it's ok in the editor, I load glt model from 

in Editor:

![image](https://github.com/atteneder/glTFast/assets/148749819/c038dc33-bf23-4bdd-94ca-8d8ae8c6cd05)

in Builds(WebGL,Android):

![image](https://github.com/atteneder/glTFast/assets/148749819/a3836d30-e49c-45e7-a4c1-4fd559936468)

**Comment by atteneder** [comment] 2023-10-28 21:38
Please don't raise issues in multiple channels/projects.

Closing as duplicate of <https://github.com/atteneder/glTFast/issues/653>.

**Closed as completed by atteneder** 2023-10-28 21:38 UTC
